[project]
name = "tdl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.3.3",
    "scipy>=1.15.2",
]

[dependency-groups]
dev = []
